name: meteorological_sandbox
description: 专业级气象沙盘模拟器 - 6大求解器算法，并行计算，60FPS渲染
version: 0.0.1+1
homepage: https://github.com/FZZhiQiu/sandbox-meteor
repository: https://github.com/FZZhiQiu/sandbox-meteor
issue_tracker: https://github.com/FZZhiQiu/sandbox-meteor/issues

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  
  # 状态管理与架构
  provider: ^6.1.2
  riverpod: ^2.5.1
  zustand: ^0.2.0
  
  # 高性能数值计算
  vector_math: ^2.1.4
  ml_linalg: ^13.11.32
  dart_numerics: ^0.0.4
  
  # 并发与并行计算
  async: ^2.11.0
  isolate: ^2.1.1
  
  # 数据存储与管理
  path_provider: ^2.1.3
  path: ^1.9.0
  shared_preferences: ^2.2.3
  sqflite: ^2.3.3+2
  
  # 高级UI组件
  cupertino_icons: ^1.0.8
  fl_chart: ^0.68.0
  syncfusion_flutter_charts: ^26.1.42
  
  # 图像与可视化
  flutter_painter: ^1.0.1
  image: ^4.2.0
  cached_network_image: ^3.3.1
  
  # 性能监控与优化
  flutter_performance_monitor: ^0.1.0
  device_info_plus: ^10.1.2
  
  # 科学计算与仿真
  units_converter: ^2.0.0
  scientific_calc: ^1.0.1
  
  # 网络与数据交换
  http: ^1.2.2
  dio: ^5.4.3+1
  
  # 工具库
  intl: ^0.19.0
  logger: ^2.4.0
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.8
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  mockito: ^5.4.4
  integration_test:
    sdk: flutter
  golden_toolkit: ^0.15.0
  benchmark_harness: ^2.2.2

flutter:
  uses-material-design: true
  
  assets:
    - assets/map/
    - assets/icons/
    - assets/color_maps/
    - assets/sample_data/
  
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Bold.ttf
          weight: 700